
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
// .env.local eerst: daar staat lokaal de DATABASE_URL. Op Vercel bestaan geen
// van beide en komt hij uit de omgeving.
config({ path: [".env.local", ".env"] });
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
  // @ts-expect-error seed is supported at runtime but not yet in the type definitions
  seed: {
    run: "tsx prisma/seed.ts",
  },
});
